"""Filter out compiler-generated and uninteresting functions."""

from __future__ import annotations

from bin2vec.extract.elf_parser import RawFunction

# Functions generated by the compiler / libc startup, not user code
BLOCKLIST_PREFIXES = (
    "__libc_csu",
    "__do_global",
    "__libc_start",
    "_start",
    "_init",
    "_fini",
    "register_tm_clones",
    "deregister_tm_clones",
    "frame_dummy",
    "__frame_dummy_init",
    "__gcc_personality",
    "__cxa_",
    "__clang_call_terminate",
    "__stack_chk_fail",
    "_dl_",
    "__x86.get_pc_thunk",
)

BLOCKLIST_EXACT = {
    "_start",
    "_init",
    "_fini",
    "__libc_csu_init",
    "__libc_csu_fini",
    "register_tm_clones",
    "deregister_tm_clones",
    "frame_dummy",
    "__do_global_dtors_aux",
    "__do_global_ctors_aux",
}

MIN_FUNCTION_SIZE = 4  # bytes


def should_keep(func: RawFunction) -> bool:
    """Return True if the function should be kept in the dataset."""
    # Skip tiny functions
    if func.size < MIN_FUNCTION_SIZE:
        return False

    # Skip exact blocklist matches
    if func.name in BLOCKLIST_EXACT:
        return False

    # Skip blocklist prefixes
    for prefix in BLOCKLIST_PREFIXES:
        if func.name.startswith(prefix):
            return False

    # Skip PLT stubs (usually named like func@plt)
    if "@plt" in func.name:
        return False

    return True
